import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from '@/components/Navbar'
import { Providers } from "@/components/Providers";
import { SidebarNav } from "@/components/SidebarNav"
import Footer from "@/components/Footer";

// import { SessionProvider } from "next-auth/react"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}
        >
          <div className="min-h-screen flex flex-col">
            <Navbar />
            
            <div className="mx-auto w-full max-w-[1920px] pt-16 px-0 lg:px-8 xl:px-16 2xl:px-32">
              <div className="flex-1 flex">
                {/* 侧边栏 */}
                <aside className="w-64 shrink-0">
                  <div className="sticky top-0 h-[calc(100vh-4rem)] custom-scrollbar overflow-y-auto py-6 px-4">
                    <SidebarNav />
                  </div>
                </aside>
                
                {/* 主内容区域 */}
                <main className="flex-1 px-4 py-6 md:px-6 lg:px-8">
                  {children}
                </main>
              </div>
            </div>

            <Footer />
          </div>
        </body>
      </html>
    </Providers>
  );
}